name: 'dbt_emissions_ghg'
version: '1.0.0'
config-version: 2

profile: 'dbt_emissions_ghg'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  qa_threshold_silver: 0.5
  qa_threshold_gold: 0.7
  ch4_min_valid: 1700
  ch4_max_valid: 2100
  alberta_min_lat: 49
  alberta_max_lat: 60
  alberta_min_lon: -120
  alberta_max_lon: -110
  h3_resolution: 6
  min_pixels_per_cell: 5

models:
  dbt_emissions_ghg:
    +pre-hook:
      - "INSTALL h3 FROM community"
      - "LOAD h3"
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
