name: 'dbt_emissions_ghg'
version: '1.0.0'
config-version: 2

profile: 'dbt_emissions_ghg'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_emissions_ghg:
    +pre-hook:
      - "INSTALL h3 FROM community"
      - "LOAD h3"
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
